fluxnova.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
  auto-deployment-enabled: true
spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
logging:
  level:
    org.finos.fluxnova.bpm.engine.ai.agent: DEBUG